version: "2.4"

services:
  srv-cast:
    image: ipiton/icecast
    build: ./front
    container_name: srv-cast
    ports:
      - 80:80
    networks:
      - icecast

  streamer-rus:
    image: ipiton/ezstream
    build: ./back
    container_name: streamer-rus
    volumes:
      - /mnt/c/music:/music
    environment:
      - PLAYLIST=/music/playlist.rus
      - MOUNTPOINT=/air.rus
    depends_on:
      - srv-cast
    networks:
      - icecast

  streamer-misc:
    image: ipiton/ezstream
    build: ./back
    container_name: streamer-misc
    volumes:
      - /mnt/c/music:/music
    environment:
      - PLAYLIST=/music/playlist.misc
      - MOUNTPOINT=/air.misc
    depends_on:
      - srv-cast
    networks:
      - icecast


networks:
  icecast:
    driver: bridge
