version: "3"


services:
  cast:
    build: ./front
    image: ipiton/icecast
    container_name: cast
    ports:
      - 80:80
    environment:
      HOSTNAME: ${HOSTNAME}

  streamer-rus:
    build: ./back
    image: ipiton/ezstream
    container_name: streamer-rus
    volumes:
      - /mnt/c/music:/music
    environment:
      PLAYLIST: /music/playlist.rus
      MOUNTPOINT: /air.rus
      STREAM_NAME: Air Radio RUS
      STREAM_URL: http://${HOSTNAME}/air.rus
      STREAM_GENRE: Russian Rock
      STREAM_DESC: Air Radio Russian Stream
    depends_on:
      - cast


  streamer-misc:
    image: ipiton/ezstream
    build: ./back
    container_name: streamer-misc
    volumes:
      - /mnt/c/music:/music
    environment:
      PLAYLIST: /music/playlist.misc
      MOUNTPOINT: /air.misc
      STREAM_NAME: Air Radio Misc
      STREAM_URL: http://${HOSTNAME}/air.misc
      STREAM_GENRE: Misc
      STREAM_DESC: Air Radio Misc Stream
    depends_on:
      - cast
